apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1s
    scrape_configs:
      - job_name: 'health-api'
        static_configs:
          - targets: ['health-api.default.svc.cluster.local:8080']
        metrics_path: /metrics
