{
 "title": "HealthSystem API",
 "description": "Basic measurements of request handling using data from prometheus-net middleware",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Instances",
    "query": "label_values(http_requests_received_total, instance)"
   },
   {
    "name": "controllers",
    "label": "Controllers",
    "query": "label_values(http_requests_received_total{instance =~ \"$instances\"}, controller)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total req/s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"health-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "( time() - process_start_time_seconds{job=\"health-api\"} ) / 60",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Active Connections (Server)",
   "type": "stat",
   "description": "Number of connections that are currently active on the server.",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_kestrel_active_connections{server_port=\"52321\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Connection Status",
   "type": "stat",
   "description": "Healthcheck of db conection",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{name=\"npgsql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "gauge",
   "description": "Number of database connections (max allowed 100 connections)",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(npgsql_db_client_connections_usage{state=\"used\"}) + sum(npgsql_db_client_connections_usage{state=\"idle\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Response Time. Show the calculation of percentile 50%, percentile 95% and percentile 99%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"health-api\"}[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"readApi\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"readApi\"}[1m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\", job=\"health-api\"}[1m])) by (code)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Requests received by endpoint",
   "type": "timeseries",
   "description": "Counts all requests, both successful and failed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint, method) (rate(http_requests_received_total{job=\"health-api\"}[1m]))\r\n",
     "legendFormat": "{{method}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Succes rate",
   "type": "timeseries",
   "description": "2xx status codes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code =~ \"2\\\\d\\\\d\", job=\"health-api\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\", job=\"readApi\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Application Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"health-api\"} / 100000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"health-api\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}