apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: secrets-config
                key: dbname
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secrets-config
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-config
                key: password
          args:
          - "-c"
          - "max_connections=500"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1500m"
            requests:
              memory: "512Mi"
              cpu: "1000m"
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc2
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP

  